parameters:
#    fedmarket_web.example.class: Fedmarket\WebBundle\Example

services:
#    fedmarket_web.example:
#        class: %fedmarket_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
